// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "KMS"
#define SECRET_PASS "10101010"

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "a3qzea7mykldu8-ats.iot.us-east-2.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIICiTCCAXGgAwIBAgIVAOxDkY3Tc/nsMeKbQ+bSMCRhmCLGMA0GCSqGSIb3DQEB
CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgU2VydmljZXMgTz1BbWF6b24uY29t
IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0yMzA5MjExMTMz
NDdaFw00OTEyMzEyMzU5NTlaMBgxFjAUBgNVBAMTDU15TUtSV2lGaTEwMTAwWTAT
BgcqhkjOPQIBBggqhkjOPQMBBwNCAAQpO84FFR5/vTdnZHxB8zZsekoyefUvddbp
/NsgW+436peXMYIvSXpq/JrBKxjBB9cbOnA9oAlVqs22HicBtubEo2AwXjAfBgNV
HSMEGDAWgBRnxZ40TjtuSwjJadUdjMeU9M0kezAdBgNVHQ4EFgQU8w3NZlBwKICQ
PsRGBjG6L3Zn+ZMwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZI
hvcNAQELBQADggEBABZTARQT4ZFkjcylXp5XsgdtXe83Z/EIa4wxT1UQ7yWI1JGe
R1Z9PGdIm01y0+5VGdgpKj4Kfdwgrk9nO1WzyNc1+4PrYihZAxXUrP//u1NCtSbl
+EtlTZ/EAnRcGUyQnZ6nNGzitnU0C6sp5MBD5OEIfT8WJyhpBCITkV4RWQYSwV32
7XKpKCwcIZruFfaTNFJbfZwo7yVs03diZHfMd6CqXHhjm0V/jNF0BG0Kyfpe1JsF
ehcVs8nNjNOrPgw1hAI3T5i2Cbxf/Vhjuk2q8JLId9fGTZs/I7hPMmw2sfQgDbcM
9Ck2zvW+flTrAm82ywjjk3gjE4+SYT+Ho3y8X6I=
-----END CERTIFICATE-----
)";
